[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
anyhow = "^1.0.82"
aws_lambda_events = "^0.15.0"
lambda_runtime = "^0.11.1"
serde = "^1.0.197"
serde_json = "^1.0.115"
tokio = "^1.37.0"
tracing = "^0.1.40"
tracing-subscriber = "^0.3.18"